-- privilégios dados em sys.orcl12

COMMIT;
ALTER USER JoaoNA quota 100M on AEBD_TABLES;
GRANT CREATE SEQUENCE TO JoaoNA;
-- EXERCICIO 4

SELECT J.ID_JOGADOR, J.NOME AS NOME, J.IDADE, C.NOME AS CLUBE, P.DESC_POSICAO AS POSICAO, L.NOME AS LIGA, C.CIDADE, C.ANO_FUNDACAO FROM JOGADOR J 
JOIN CLUBE C ON J.ID_CLUBE = C.ID_CLUBE
JOIN POSICAO P ON J.ID_POSICAO = P.ID_POSICAO
JOIN LIGA L ON C.ID_LIGA = L.ID_LIGA;

CREATE VIEW JOGADOR_VIEW (ID_JOGADOR, NOME, IDADE, NOME_CLUBE, POSICAO, NOME_LIGA, CIDADE_CLUBE, ANO_DE_FUNDACAO)
AS (SELECT J.ID_JOGADOR, J.NOME AS NOME, J.IDADE, C.NOME AS CLUBE, P.DESC_POSICAO AS POSICAO, L.NOME AS LIGA, C.CIDADE, C.ANO_FUNDACAO FROM JOGADOR J 
JOIN CLUBE C ON J.ID_CLUBE = C.ID_CLUBE
JOIN POSICAO P ON J.ID_POSICAO = P.ID_POSICAO
JOIN LIGA L ON C.ID_LIGA = L.ID_LIGA);

SELECT * FROM JOGADOR_VIEW;

-- EXERCICIO 5

SELECT J.NOME FROM JOGADOR J 
JOIN CLUBE C ON J.ID_CLUBE = C.ID_CLUBE
JOIN LIGA L ON C.ID_LIGA = L.ID_LIGA
JOIN POSICAO P ON J.ID_POSICAO = P.ID_POSICAO
WHERE L.NOME = 'II Liga' AND P.DESC_POSICAO = 'Defesa Direito';

-- EXERCICIO 6

SELECT J.NOME FROM JOGADOR J
JOIN POSICAO P ON P.ID_POSICAO = J.ID_POSICAO
JOIN CLUBE C ON C.ID_CLUBE = J.ID_CLUBE
JOIN LIGA L ON L.ID_LIGA = C.ID_CLUBE
WHERE L.NOME != 'II Liga' AND J.IDADE < 27 AND P.DESC_POSICAO = 'Trinco';

-- EXERCICIO 7

SELECT T.ID_TREINADOR, T.NOME, C.NOME, CA.DESC_CARGO FROM TREINADOR T
JOIN CLUBE C ON T.ID_CLUBE = C.ID_CLUBE
JOIN CARGO CA ON T.ID_CARGO = CA.ID_CARGO;

CREATE VIEW TREINADOR_VIEW (ID_TREINADOR, NOME_TREINADOR, NOME_CLUBE, DESCRICAO_DO_CARGO)
AS (SELECT T.ID_TREINADOR, T.NOME, C.NOME, CA.DESC_CARGO FROM TREINADOR T
JOIN CLUBE C ON T.ID_CLUBE = C.ID_CLUBE
JOIN CARGO CA ON T.ID_CARGO = CA.ID_CARGO);

SELECT * FROM TREINADOR_VIEW;

-- EXERCICIO 8

SELECT T.NOME, C.NOME, CA.DESC_CARGO, C.CIDADE, C.ANO_FUNDACAO FROM TREINADOR T
JOIN CLUBE C ON C.ID_CLUBE = T.ID_CLUBE
JOIN CARGO CA ON CA.ID_CARGO = T.ID_CARGO
WHERE C.ANO_FUNDACAO > 1945;

-- EXERCICIO 9

-- CRIADA COM INTERFACE DO SQLDEVELOPER

-- EXERCICIO 10

